version: '3.8'

services:
  # 1. 云端数据库 (PostgreSQL)
  db:
    image: postgres:15
    container_name: sentinel_postgres
    environment:
      - POSTGRES_DB=sentinel_db
      - POSTGRES_USER=sentinel_user
      - POSTGRES_PASSWORD=sentinel_password
    ports:
      - "5433:5432"  # 意思是：把电脑的5433转到容器的5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. 高速缓存 (Redis)
  redis:
    image: redis:7
    container_name: sentinel_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: